### ISSUE TITLE
Cannot find module `babel-plugin-ast-literal`

### ISSUE THREAD

**Issue by MicheleBertoli** [andreypopp/react-css-components#3]
Hello @andreypopp, thanks for your library.

I'm trying to add it to my [css-in-js](https://github.com/MicheleBertoli/css-in-js) repo but I get the following error:

> ERROR in Cannot find module '/Users/andreypopp/Workspace/react-css-components/node_modules/.store/babel-plugin-ast-literal@0.5.3/_/lib/liftToAST.js'

The version I'm using is: 0.6.6.

**Comment by andreypopp** [comment]
Fixed in 0.6.8. Thanks for looking into it!
