### ISSUE TITLE
Classes are not applied to elements

### ISSUE THREAD

**Issue by MicheleBertoli** [andreypopp/react-css-components#4]
Hello @andreypopp.
Now that #3 is fixed, I was trying to use it but I couldn't make it work.

So, I cloned the repo and run the following commands:

``` bash
npm install
make build
cd examples/webpack
npm install
npm run build
open index.html
```

And I got the output without classes:

``` html
<div id="main">
  <div data-reactroot="">
    <div>Header</div>
    <div>Content</div>
  </div>
</div>
```

Environment:

``` bash
node --version
v5.11.0
npm --version
3.8.6
```

Am I doing something wrong?

**Comment by andreypopp** [comment]
Wow, that's embarrassing...

The default configuration is invalid (in my project which uses react-css-components I use custom config with CSS extraction enabled). I've published 0.6.9 to fix the issue.
