### ISSUE TITLE
Non-div elements

### ISSUE THREAD

**Issue by jacobp100** [andreypopp/react-css-components#5]
Important as divs are not permissible in some elements (i.e. buttons)

**Comment by andreypopp** [comment]
Supported through the `base` property:

```
Button {
  base: button;
  color: red;
}
```

In fact if you have a composite component which accepts `className` you can even use it as a base:

```
FancyButton {
  base: ./buttons/ButtonBase;
  color: red;
}
```

Leaving this issue open not to forget to document this.

**Comment by andreypopp** [comment]
Documented!
