### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by MicheleBertoli** [andreypopp/react-css-components#7]
Hello @andreypopp, I've added the library to [MicheleBertoli/css-in-js](https://github.com/MicheleBertoli/css-in-js).
To make it work locally, I had to install some extra dependencies: `style-loader`, `css-loader` and `babel-plugin-transform-object-rest-spread`.
I guess it would be nice to have those deps installed automatically with the package.
Thanks!

**Comment by andreypopp** [comment]
Thanks!

Reference #1

**Comment by andreypopp** [comment]
Done
